check_update_on_start: true
games_path: ""
insteadman_path: ""
interpreter_command: ""
lang: ru
repositories:
- name: official
  url: http://instead.syscall.ru/pool/game_list.xml
- name: instead-games
  url: http://instead-games.ru/xml.php
- name: instead-games-sandbox
  url: http://instead-games.ru/xml2.php
use_builtin_interpreter: true
version: 3.0.0
